spring:
  profiles:
    active: ${PROFILE:development}
  cloud:
    gcp:
      storage:
        project-id: ${GCP_PROJECT_ID:hs-flow-develop}
        credentials:
          location: file:${GCP_KEY_PATH:hs-flow-develop-3c715f83707a.json}
server:
  port: 8084

bucketname: hs-flow-develop.appspot.com
